name: Maven Package

on:
  release:
    types: [created]  # Esto ejecuta el flujo de trabajo cuando se crea una nueva release en GitHub

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read  # Para acceder al c贸digo fuente
      packages: write  # Para poder subir el paquete a GitHub Packages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout del c贸digo del repositorio

    - name: Set up JDK 11
      uses: actions/setup-java@v4  # Configura JDK 11
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github  # Este 'server-id' debe coincidir con el id configurado en tu 'pom.xml' (en este caso 'github')
        settings-path: ${{ github.workspace }}  # Ubicaci贸n para el archivo settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml  # Construye el paquete usando Maven

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml  # Publica el paquete en GitHub Packages
      env:
        GITHUB_TOKEN: ${{ github.token }}  # Usa el token de GitHub para autenticaci贸n
